version: '3'
services:
    bitacora:
        image: bitacora
        build: .
        environment:
            - RUST_LOG=info
        ports:
            - 3000:3000
        command: [
            "--web3", "http://web3:8545",
            "--contracts-base", "/app/contracts/contracts",
            "--contract-address", "0xabEC58E12DdB39CEDC34755299Ea9b4B25631945",
            "--private-key", "a8112819434042a710ecc16997caaa0347369969c2e562ac204a24d9be000259",
            "--redis", "redis://redis:6379",
        ]
        depends_on:
            - web3
            - redis
            - web3_deployer
    redis:
        image: redis
        volumes:
            - redis:/data
        command: ["--save", "5", "1", "--loglevel", "warning"]
    verify-portal:
        image: verify-portal
        build: ./verify-portal
        ports:
            - 80:80
    web3:
        image: clique-devnet
        build: ./devnet
    web3_deployer:
        image: bitacora_deployer
        build: ./contracts
volumes:
    redis: